// frontend/src/components/Slider.vue
<script setup>
    const props = defineProps({
        name: String,
        min: Number,
        max: Number,
    })

    import { ref, onMounted } from 'vue'

    const val = ref(0);

    onMounted(() => {
        val.value = (Number(props.max) + Number(props.min))/2;
    })

    function showVal() {
        console.log(val.value);
    }

</script>

<template>
    <div class="p-2 text-xl py-1 font-bold">
        <label :for="`range-${props.name}`" class="block mb-2 text-left text-gray-900 dark:text-white">{{ props.name }}: {{ val }}</label>
        <input 
            :id="`range-${props.name}`" 
            type="range" 
            :min="props.min" 
            :max="props.max" 
            v-model="val"
            @change="showVal"
            class="range accent-cyan-700 w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer dark:bg-slate-700"
        />
    </div>
</template>

// frontend/src/components/Slider.jsx
import { useState } from "react";

function Slider(props) {

    let [value, setValue] = useState(0.5*props.min + 0.5*props.max);

    function handleChange(event) {
        setValue(event.target.value);
    }

    return (
        <>
        <div className="p-2 text-xl py-1 font-bold">
            <label htmlFor={"slider-" + props.label} className="block mb-2 text-left text-gray-900 dark:text-white"> {props.label}: {value} </label>
            <input 
                id={"slider-" + props.label} 
                type="range" 
                min={props.min}
                max={props.max} 
                value={value}
                onChange={handleChange}
                className="range accent-cyan-700 w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer dark:bg-slate-700"
            />
        </div>
        </>
    );
}

export default Slider;
