// frontend/src/App.jsx
import { useState } from 'react'
import './App.css'
import MainToggle from './components/MainToggle'
import ModeSelect from './components/ModeSelect'
import Slider from './components/Slider'

function App() {
  const [appData, setAppData] = useState({
    onOff: false,
    modes: ["foo", "bar", "baz", "boo"],
    selected: "bar",
    parameters: {},
  });

  let connData = {
    mode: import.meta.env.MODE,
    ws_addr: undefined,
  }
  if (connData.mode == "production") {
    connData.ws_addr = "/ws"
  } else {
    connData.ws_addr = "https://localhost:8000/ws"
  }

  return (
    <>
      <h1 className="text-3xl font-bold bg-cyan-700 rounded-lg">
          Christmas Lights
      </h1>
      <MainToggle appData={appData} setAppData={setAppData} />
      <ModeSelect appData={appData} setAppData={setAppData} />
      <h2 className="text-xl font-bold">State</h2>
      <p>{ appData.onOff? "on": "off" }</p>
      <p> mode: { appData.selected? appData.selected : "none" }</p>
      <Slider label="Foo" min="25" max="175" />
    </>
  )
}

export default App

// frontend/src/App.vue
<script setup>
import Toggle from './components/Toggle.vue'
import Slider from './components/Slider.vue'
import Select from './components/Select.vue'
</script>

<template>
  <h1 class="text-3xl font-bold bg-cyan-700 rounded-lg">
    Hello, world!
  </h1>
  <Toggle left_text="Off" right_text="On"/>
  <Select name="mode" label="Mode:" options="ABC" selected="A" />
  <Slider name="foo" min="0" max="100" />
  <Slider name="bar" min="0" max="100" />
  <Slider name="baz" min="100" max="250" />

</template>
